# 运行环境，Travis 会自动提供这个环境
os: linux
sudo: false
language: python

# 指定版本
python:
  - "3.6"

# 安装依赖
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt

# 执行脚本
script:
  - python main.py
cache:
  - pip

# 将script执行结果推送到 master 分支上
after_script:
  # 初始化git
  - git init
  # user.name 和 user.email 让 travis 能登录你的 github
  - git config user.name "liukai"
  - git config user.email "liukai@liukai.com"
  - git add .
  - git commit -m "docs:update articles"
  # GH_TOKEN 为你的 github 允许 travis 访问生成的凭证
  # GH_REF 告诉 travis 往哪个仓库推送代码，具体值下面配置
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

# 监视的分支，当该分支发生变化时，自动构建
branches:
  only:
    - develop

notifications:
  email: false


env:
  global:
    # 定义往哪个仓库推送代码，注意事项见下面
    - GH_REF: github.com/liukaida/python_travis
